rvm:
  - 1.9.3
  - 2.0.0

services:
  - postgresql

bundler_args: --without development

before_script:
  - psql -c "CREATE DATABASE chronomodel;" -U postgres

script: bundle exec rake TEST_CONFIG=./spec/config.travis.yml
