rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

services:
  - postgresql

addons:
  postgresql: 9.3

bundler_args: --without development

before_install:
  - sudo apt-get update
  - sudo apt-get install postgresql-plpython-9.3

before_script:
  - psql -c "CREATE DATABASE chronomodel;" -U postgres

script: bundle exec rake TEST_CONFIG=./spec/config.travis.yml
